### ISSUE TITLE
`@freetube/yt-channel-info will be archived`

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [kop7er/SinksBot#2]
Hello,

We are planning on archiving the @freetube/yt-channel-info module in the near future. I thought I'd reach out to the modules dependents to let them know so they can migrate to a new module if they would like.

FreeTube is switching to https://github.com/LuanRT/YouTube.js but I'm sure there are other modules that you could switch to.

https://github.com/FreeTubeApp/yt-channel-info/issues/166

**Comment by kop7er** [comment]
_Just leaving a note here to close the issue._

The `@freetube/yt-channel-info` package will continue to be used in the project and will not be replaced by a different one.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
We have already migrated to youtube.js. All we have to do is to put out a new release and archive the repo.
